/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesIdRouteImport } from './routes/packages.$id'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated.account'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated.account.index'
import { Route as AuthenticatedBookIdRouteImport } from './routes/_authenticated.book.$id'
import { Route as AuthenticatedAccountWishlistRouteImport } from './routes/_authenticated.account.wishlist'
import { Route as AuthenticatedAccountTravelersRouteImport } from './routes/_authenticated.account.travelers'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated.account.profile'
import { Route as AuthenticatedAccountBookingsRouteImport } from './routes/_authenticated.account.bookings'
import { Route as AuthenticatedBookSuccessBookingIdRouteImport } from './routes/_authenticated.book.success.$bookingId'
import { Route as AuthenticatedAccountAdminTourCategoriesRouteImport } from './routes/_authenticated.account.admin.tour-categories'
import { Route as AuthenticatedAccountAdminRecentGalleryRouteImport } from './routes/_authenticated.account.admin.recent-gallery'
import { Route as AuthenticatedAccountAdminPopularToursRouteImport } from './routes/_authenticated.account.admin.popular-tours'
import { Route as AuthenticatedAccountAdminPopularDestinationsRouteImport } from './routes/_authenticated.account.admin.popular-destinations'
import { Route as AuthenticatedAccountAdminPlanYourTripRouteImport } from './routes/_authenticated.account.admin.plan-your-trip'
import { Route as AuthenticatedAccountAdminHeroRouteImport } from './routes/_authenticated.account.admin.hero'
import { Route as AuthenticatedAccountAdminAchievementsRouteImport } from './routes/_authenticated.account.admin.achievements'

const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIdRoute = PackagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PackagesRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedBookIdRoute = AuthenticatedBookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountWishlistRoute =
  AuthenticatedAccountWishlistRouteImport.update({
    id: '/wishlist',
    path: '/wishlist',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountTravelersRoute =
  AuthenticatedAccountTravelersRouteImport.update({
    id: '/travelers',
    path: '/travelers',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountBookingsRoute =
  AuthenticatedAccountBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedBookSuccessBookingIdRoute =
  AuthenticatedBookSuccessBookingIdRouteImport.update({
    id: '/book/success/$bookingId',
    path: '/book/success/$bookingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountAdminTourCategoriesRoute =
  AuthenticatedAccountAdminTourCategoriesRouteImport.update({
    id: '/admin/tour-categories',
    path: '/admin/tour-categories',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountAdminRecentGalleryRoute =
  AuthenticatedAccountAdminRecentGalleryRouteImport.update({
    id: '/admin/recent-gallery',
    path: '/admin/recent-gallery',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountAdminPopularToursRoute =
  AuthenticatedAccountAdminPopularToursRouteImport.update({
    id: '/admin/popular-tours',
    path: '/admin/popular-tours',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountAdminPopularDestinationsRoute =
  AuthenticatedAccountAdminPopularDestinationsRouteImport.update({
    id: '/admin/popular-destinations',
    path: '/admin/popular-destinations',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountAdminPlanYourTripRoute =
  AuthenticatedAccountAdminPlanYourTripRouteImport.update({
    id: '/admin/plan-your-trip',
    path: '/admin/plan-your-trip',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountAdminHeroRoute =
  AuthenticatedAccountAdminHeroRouteImport.update({
    id: '/admin/hero',
    path: '/admin/hero',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountAdminAchievementsRoute =
  AuthenticatedAccountAdminAchievementsRouteImport.update({
    id: '/admin/achievements',
    path: '/admin/achievements',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRouteWithChildren
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/packages/$id': typeof PackagesIdRoute
  '/account/bookings': typeof AuthenticatedAccountBookingsRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/travelers': typeof AuthenticatedAccountTravelersRoute
  '/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/book/$id': typeof AuthenticatedBookIdRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/account/admin/achievements': typeof AuthenticatedAccountAdminAchievementsRoute
  '/account/admin/hero': typeof AuthenticatedAccountAdminHeroRoute
  '/account/admin/plan-your-trip': typeof AuthenticatedAccountAdminPlanYourTripRoute
  '/account/admin/popular-destinations': typeof AuthenticatedAccountAdminPopularDestinationsRoute
  '/account/admin/popular-tours': typeof AuthenticatedAccountAdminPopularToursRoute
  '/account/admin/recent-gallery': typeof AuthenticatedAccountAdminRecentGalleryRoute
  '/account/admin/tour-categories': typeof AuthenticatedAccountAdminTourCategoriesRoute
  '/book/success/$bookingId': typeof AuthenticatedBookSuccessBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/packages/$id': typeof PackagesIdRoute
  '/account/bookings': typeof AuthenticatedAccountBookingsRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/travelers': typeof AuthenticatedAccountTravelersRoute
  '/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/book/$id': typeof AuthenticatedBookIdRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/account/admin/achievements': typeof AuthenticatedAccountAdminAchievementsRoute
  '/account/admin/hero': typeof AuthenticatedAccountAdminHeroRoute
  '/account/admin/plan-your-trip': typeof AuthenticatedAccountAdminPlanYourTripRoute
  '/account/admin/popular-destinations': typeof AuthenticatedAccountAdminPopularDestinationsRoute
  '/account/admin/popular-tours': typeof AuthenticatedAccountAdminPopularToursRoute
  '/account/admin/recent-gallery': typeof AuthenticatedAccountAdminRecentGalleryRoute
  '/account/admin/tour-categories': typeof AuthenticatedAccountAdminTourCategoriesRoute
  '/book/success/$bookingId': typeof AuthenticatedBookSuccessBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/packages/$id': typeof PackagesIdRoute
  '/_authenticated/account/bookings': typeof AuthenticatedAccountBookingsRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/account/travelers': typeof AuthenticatedAccountTravelersRoute
  '/_authenticated/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/_authenticated/book/$id': typeof AuthenticatedBookIdRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/account/admin/achievements': typeof AuthenticatedAccountAdminAchievementsRoute
  '/_authenticated/account/admin/hero': typeof AuthenticatedAccountAdminHeroRoute
  '/_authenticated/account/admin/plan-your-trip': typeof AuthenticatedAccountAdminPlanYourTripRoute
  '/_authenticated/account/admin/popular-destinations': typeof AuthenticatedAccountAdminPopularDestinationsRoute
  '/_authenticated/account/admin/popular-tours': typeof AuthenticatedAccountAdminPopularToursRoute
  '/_authenticated/account/admin/recent-gallery': typeof AuthenticatedAccountAdminRecentGalleryRoute
  '/_authenticated/account/admin/tour-categories': typeof AuthenticatedAccountAdminTourCategoriesRoute
  '/_authenticated/book/success/$bookingId': typeof AuthenticatedBookSuccessBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/packages'
    | '/account'
    | '/auth/login'
    | '/auth/register'
    | '/packages/$id'
    | '/account/bookings'
    | '/account/profile'
    | '/account/travelers'
    | '/account/wishlist'
    | '/book/$id'
    | '/account/'
    | '/account/admin/achievements'
    | '/account/admin/hero'
    | '/account/admin/plan-your-trip'
    | '/account/admin/popular-destinations'
    | '/account/admin/popular-tours'
    | '/account/admin/recent-gallery'
    | '/account/admin/tour-categories'
    | '/book/success/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/packages'
    | '/auth/login'
    | '/auth/register'
    | '/packages/$id'
    | '/account/bookings'
    | '/account/profile'
    | '/account/travelers'
    | '/account/wishlist'
    | '/book/$id'
    | '/account'
    | '/account/admin/achievements'
    | '/account/admin/hero'
    | '/account/admin/plan-your-trip'
    | '/account/admin/popular-destinations'
    | '/account/admin/popular-tours'
    | '/account/admin/recent-gallery'
    | '/account/admin/tour-categories'
    | '/book/success/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/packages'
    | '/_authenticated/account'
    | '/auth/login'
    | '/auth/register'
    | '/packages/$id'
    | '/_authenticated/account/bookings'
    | '/_authenticated/account/profile'
    | '/_authenticated/account/travelers'
    | '/_authenticated/account/wishlist'
    | '/_authenticated/book/$id'
    | '/_authenticated/account/'
    | '/_authenticated/account/admin/achievements'
    | '/_authenticated/account/admin/hero'
    | '/_authenticated/account/admin/plan-your-trip'
    | '/_authenticated/account/admin/popular-destinations'
    | '/_authenticated/account/admin/popular-tours'
    | '/_authenticated/account/admin/recent-gallery'
    | '/_authenticated/account/admin/tour-categories'
    | '/_authenticated/book/success/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$id': {
      id: '/packages/$id'
      path: '/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof PackagesIdRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/book/$id': {
      id: '/_authenticated/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof AuthenticatedBookIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/wishlist': {
      id: '/_authenticated/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AuthenticatedAccountWishlistRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/travelers': {
      id: '/_authenticated/account/travelers'
      path: '/travelers'
      fullPath: '/account/travelers'
      preLoaderRoute: typeof AuthenticatedAccountTravelersRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/bookings': {
      id: '/_authenticated/account/bookings'
      path: '/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AuthenticatedAccountBookingsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/book/success/$bookingId': {
      id: '/_authenticated/book/success/$bookingId'
      path: '/book/success/$bookingId'
      fullPath: '/book/success/$bookingId'
      preLoaderRoute: typeof AuthenticatedBookSuccessBookingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/admin/tour-categories': {
      id: '/_authenticated/account/admin/tour-categories'
      path: '/admin/tour-categories'
      fullPath: '/account/admin/tour-categories'
      preLoaderRoute: typeof AuthenticatedAccountAdminTourCategoriesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/admin/recent-gallery': {
      id: '/_authenticated/account/admin/recent-gallery'
      path: '/admin/recent-gallery'
      fullPath: '/account/admin/recent-gallery'
      preLoaderRoute: typeof AuthenticatedAccountAdminRecentGalleryRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/admin/popular-tours': {
      id: '/_authenticated/account/admin/popular-tours'
      path: '/admin/popular-tours'
      fullPath: '/account/admin/popular-tours'
      preLoaderRoute: typeof AuthenticatedAccountAdminPopularToursRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/admin/popular-destinations': {
      id: '/_authenticated/account/admin/popular-destinations'
      path: '/admin/popular-destinations'
      fullPath: '/account/admin/popular-destinations'
      preLoaderRoute: typeof AuthenticatedAccountAdminPopularDestinationsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/admin/plan-your-trip': {
      id: '/_authenticated/account/admin/plan-your-trip'
      path: '/admin/plan-your-trip'
      fullPath: '/account/admin/plan-your-trip'
      preLoaderRoute: typeof AuthenticatedAccountAdminPlanYourTripRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/admin/hero': {
      id: '/_authenticated/account/admin/hero'
      path: '/admin/hero'
      fullPath: '/account/admin/hero'
      preLoaderRoute: typeof AuthenticatedAccountAdminHeroRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/admin/achievements': {
      id: '/_authenticated/account/admin/achievements'
      path: '/admin/achievements'
      fullPath: '/account/admin/achievements'
      preLoaderRoute: typeof AuthenticatedAccountAdminAchievementsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountBookingsRoute: typeof AuthenticatedAccountBookingsRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountTravelersRoute: typeof AuthenticatedAccountTravelersRoute
  AuthenticatedAccountWishlistRoute: typeof AuthenticatedAccountWishlistRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedAccountAdminAchievementsRoute: typeof AuthenticatedAccountAdminAchievementsRoute
  AuthenticatedAccountAdminHeroRoute: typeof AuthenticatedAccountAdminHeroRoute
  AuthenticatedAccountAdminPlanYourTripRoute: typeof AuthenticatedAccountAdminPlanYourTripRoute
  AuthenticatedAccountAdminPopularDestinationsRoute: typeof AuthenticatedAccountAdminPopularDestinationsRoute
  AuthenticatedAccountAdminPopularToursRoute: typeof AuthenticatedAccountAdminPopularToursRoute
  AuthenticatedAccountAdminRecentGalleryRoute: typeof AuthenticatedAccountAdminRecentGalleryRoute
  AuthenticatedAccountAdminTourCategoriesRoute: typeof AuthenticatedAccountAdminTourCategoriesRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountBookingsRoute: AuthenticatedAccountBookingsRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountTravelersRoute: AuthenticatedAccountTravelersRoute,
  AuthenticatedAccountWishlistRoute: AuthenticatedAccountWishlistRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedAccountAdminAchievementsRoute:
    AuthenticatedAccountAdminAchievementsRoute,
  AuthenticatedAccountAdminHeroRoute: AuthenticatedAccountAdminHeroRoute,
  AuthenticatedAccountAdminPlanYourTripRoute:
    AuthenticatedAccountAdminPlanYourTripRoute,
  AuthenticatedAccountAdminPopularDestinationsRoute:
    AuthenticatedAccountAdminPopularDestinationsRoute,
  AuthenticatedAccountAdminPopularToursRoute:
    AuthenticatedAccountAdminPopularToursRoute,
  AuthenticatedAccountAdminRecentGalleryRoute:
    AuthenticatedAccountAdminRecentGalleryRoute,
  AuthenticatedAccountAdminTourCategoriesRoute:
    AuthenticatedAccountAdminTourCategoriesRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedBookIdRoute: typeof AuthenticatedBookIdRoute
  AuthenticatedBookSuccessBookingIdRoute: typeof AuthenticatedBookSuccessBookingIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedBookIdRoute: AuthenticatedBookIdRoute,
  AuthenticatedBookSuccessBookingIdRoute:
    AuthenticatedBookSuccessBookingIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PackagesRouteChildren {
  PackagesIdRoute: typeof PackagesIdRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesIdRoute: PackagesIdRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PackagesRoute: PackagesRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
